name: Download logs for analysis

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: evaluation
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: 18
            cache: 'yarn'
            cache-dependency-path: evaluation/yarn.lock
      - run: yarn --frozen-lockfile
      - run: node -r @swc-node/register ./src/downloadLogs.ts
        env:
            BAMBOO_USERNAME: ${{ secrets.BAMBOO_USERNAME }}
            BAMBOO_PASSWORD: ${{ secrets.BAMBOO_PASSWORD }}
            BAMBOO_TOKEN: ${{ secrets.BAMBOO_TOKEN }}
      - uses: EndBug/add-and-commit@v9
        with:
          message: Update Logs
