name: Trigger analysis runs

on:
  schedule:
    - cron: "0 1-5 * * *"
  workflow_dispatch:
    inputs:
      maxRuns:
        description: 'Maximum number of runs to trigger'
        required: true
        default: '16'

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: evaluation
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: 18
            cache: yarn
            cache-dependency-path: evaluation/yarn.lock
      - run: yarn
      - run: npx ts-node-esm ./src/triggerRuns.ts
        env:
          BAMBOO_USERNAME: ${{ secrets.BAMBOO_USERNAME }}
          BAMBOO_PASSWORD: ${{ secrets.BAMBOO_PASSWORD }}
          MAX_RUNS: ${{ github.event.inputs.maxRuns || 16 }}
